export const questions = [
  "What AI stocks have the highest market cap?",
  "Calculate the average daily trading volume for Apple stock in the past month",
  "List companies with revenue growth of more than 20% year-over-year",
  "Which stock had the highest volatility in the past quarter?",
  "Find all stocks that pay dividends with a yield above 3%",
  "What was the total market cap of the S&P 500 at the end of last quarter?",
  "Find stocks trading below their 200-day moving average",
  "Which sector had the best performance in the most recent quarter?",
  "List all stocks with a beta greater than 1.5",
  "Find companies with increasing profit margins over the last 3 years",
  "Which bank stocks have the lowest price-to-book ratios?",
  "What were the top 10 best performing stocks of last year?",
  "Which EV companies have the highest debt-to-equity ratios?",
  "What is the correlation in returns between SPY and Reddit (RDDT) in the past 6 months? What about the past 6 weeks?",
  "What non-technology stocks have increased their revenue and net income every year for the past 3 years?",
  "What cloud computing stocks have increased their free cash flow every quarter for the past 4 quarters?",
  "What companies have the highest 10-year revenue CAGR?",
  "What is the average price-to-earnings ratio for the S&P 500?",
  "What stocks with a market cap above $100 billion have the highest 5-year net income CAGR?",
  "What technology stocks with a market cap between $100 billion and $500 billion are the furthest below their 200-day moving average?",
  "What AI stocks have the highest 90 day standard deviation?",
  "find large cap stocks that have high free cash flows, has PEG ratio under 1 and current P/E is low relative to the company's own typical P/E range over the past 5-10 years.",
  "find mid cap stocks that have high free cash flows, has PEG ratio under 1 and current P/E is low relative to the company's own typical P/E range over the past 5-10 years.",
  "find small cap stocks that have high free cash flows, has PEG ratio under 1 and current P/E is low relative to the company's own typical P/E range over the past 5-10 years.",
  "Analyze the MAG7 fundamentally for their past earnings",
  "What profitable healthcare stocks have the lowest market cap?",
  "What was Microsoft's free cash flow in 2024?",
  "What was Apple's free cash flow in the past 4 quarters?",
  "What stock has the highest total assets?",
  "What financial services stock have the highest 1-year net income increase (in terms of dollars)?",
  "What automotice stock have the highest 1-year net income increase (in terms of percentage)?",
  "What are the most fundamentally strong space stocks?",
  "What is the average P/E ratio, P/S ratio, and FcF of Meta, Amazon, Google, Netflix, Nvidia, and Microsoft?",
  "What industries had the highest percent gain in 2024?",
  "What stocks had the highest drop (in terms of dollars) in the past 2 weeks?",
  "What stocks had the highest drop (in terms of percentage) in the past 2 weeks?",
  "What stocks with a market cap between $10 and $250 billion have a 5-year net income CAGR of at least 15%?",
  "What consumer goods stocks with a net income above $10 billion had the highest percent drop in the past 2 months?",
  "What airline stocks are up the most year-to-date?",
  "What semiconductor stocks have at least a 20% net income increase from 2022 to 2024? Sort by market cap descending",
  "What AI stocks with a 4 year consistently increasing net income have the lowest 14 day RSI?",
  "What cloud computing stocks with a fundamental ranking between 3 and 4 have the most number of standard deviations from their 200 day average price?",
  "What banking stocks are the most below their 7 day exponential moving average?",
  "What semiconductor stocks have the highest 7 day increase in market cap in 2022?",
  "What AI stocks other than the MAG7 have the highest net income increase from 2022 to 2024?",
  "What stocks are the most number of standard deviations from their 200 day average price?",
  "What AI stocks are between 1 and 2 standard deviations from their 20 day average price in either direction?",
  "What quantum computing stocks have the highest drawdown in the past 2 weeks?",
  "What crypto stocks have the highest 7 day increase in market cap in 2022?",
  "What cryptocurrencies have the largest 1-day gain in the past 2 weeks?",
  "What is the average gain, market cap, P/E ratio, and revenue of the cryptoucrrency industry?",
  "What AI stocks have the highest revenue difference between the average AI revenue and their own revenue?",
  "What biology related stocks have the highest revenue difference between the average biology related free cash flow and their own free cash flow in 2023?",
  "Which stocks have RSI's that are the most significantly different from the average RSI of the S&P 500?",
  "Which stocks have RSI's that are the most significantly different from their 30 day average RSI?",
  "What stocks have increased their revenue every quarter for the past 4 quarters?",
  "What stocks have increased their net income every year for the past 4 years?",
  "What stocks have increased their free cash flow every quarter for the past 4 quarters and every year for the past 4 years and have a market cap between $10 and $250 billion?",
  "What is the correlation between net income change and price change? Group by 2022, 2023, 2024, and all together.",
  "What is the correlation between SPY's return and Bitcoin's return in the past 2 weeks? 2 months? 2 years? 5 years?",
  "What non-tech stocks have the highest dividend yield? Filter to only stocks that have increased their dividend amount every year for the past 4 years.",
  "What tech stocks have with a lower than average price volatility have a 10% CAGR for their price in the past 5 years and a dividend yield above 2%?",
  "Which stocks had a golden cross (50-day MA crossing above 200-day MA) in the past month?",
  "Which sectors have the highest Sharpe ratio over the past 2 years?",
  "Which stocks had 10 or more 3% intraday drawdowns in the last month?",
  "Which semiconductor stocks have EV/EBITDA under 10 and debt-to-equity ratio under 0.5?",
  "Rank S&P 500 stocks by Altman Z-Score from most to least distressed",
  "Which companies had revenue growth decelerate for 2 straight quarters?",
  "Which stock in each industry had the smallest 12-month drawdown in the past 5 years?",
  "Which stock pairs have return correlation > 0.8 and are cointegrated?",
  "Which dividend-paying stocks have payout ratios over 80% and stable free cash flow?",
  "Which FAANG company had the biggest gross margin drop YoY in any quarter?",
  "Which high-beta companies were unprofitable on net income but profitable on EBITDA?",
  "Compare YoY growth in total assets for healthcare vs. financial services over 3 years",
  "Which companies hit $100B market cap for the first time in 2024 and how did they perform?",
  "Which companies had the largest dollar increase in free cash flow from 2023 to 2024?",
  "Rank S&P 500 by average EBITDA margin over the past 8 quarters",
  "Which tech companies had book-to-market > 1.5 and Altman Z > 3?",
  "Which companies are currently in the 95th percentile of 30-day price volatility?",
  "In the past 5 years, on 1% SPY move days, which stocks moved in the opposite direction?",
  "Which stocks had volume spikes > 3x 30-day average volume in the past month?",
  "Which companies have at least 2 years of dividend history and the highest dividend CAGR?",
  "Sort the MAG7 by their 5-year revenue CAGR",
  "What are the top 5 stocks by market cap with a 3-year net income CAGR greater than their 5-year net income CAGR and a net income above $1 billion?",
  "What are the top 10 stocks by revenue with a 2025 percent gain so far greater than its total 2024 percent gain? Sort by market cap descending",
  "What biotech stocks have the highest 1-year net income increase (in terms of dollars)?",
  "What EV stocks had the highest drawdown in the past year?",
  "What stocks have increased 5% or more this week and had a volume spike of 3x their normal volume?",
  "What stock with a market cap of below $50 billion in 2023 have a market cap above $150 billion now?",
];
