export const questions = [
  "What AI stocks have the highest market cap?",
  "Calculate the average daily trading volume for Apple stock in the past month",
  "List companies with revenue growth of more than 20% year-over-year",
  "Which stock had the highest volatility in the past quarter?",
  "Find all stocks that pay dividends with a yield above 3%",
  "What was the total market cap of the S&P 500 at the end of last quarter?",
  "Find stocks trading below their 200-day moving average",
  "Which sector had the best performance in the most recent quarter?",
  "List all stocks with a beta greater than 1.5",
  "Find companies with increasing profit margins over the last 3 years",
  "Which bank stocks have the lowest price-to-book ratios?",
  "What were the top 10 best performing stocks of last year?",
  "Which EV companies have the highest debt-to-equity ratios?",
  "What is the correlation in returns between SPY and Reddit (RDDT) in the past 6 months? What about the past 6 weeks?",
  "What non-technology stocks have increased their revenue and net income every year for the past 3 years?",
  "What cloud computing stocks have increased their free cash flow every quarter for the past 4 quarters?",
  "What companies have the highest 10-year revenue CAGR?",
  "What is the average price-to-earnings ratio for the S&P 500?",
  "What stocks with a market cap above $100 billion have the highest 5-year net income CAGR?",
  "What technology stocks with a market cap between $100 billion and $500 billion are the furthest below their 200-day moving average?",
  "What AI stocks have the highest 90 day standard deviation?",
  "find large cap stocks that have high free cash flows, has PEG ratio under 1 and current P/E is low relative to the company's own typical P/E range over the past 5-10 years.",
  "find mid cap stocks that have high free cash flows, has PEG ratio under 1 and current P/E is low relative to the company's own typical P/E range over the past 5-10 years.",
  "find small cap stocks that have high free cash flows, has PEG ratio under 1 and current P/E is low relative to the company's own typical P/E range over the past 5-10 years.",
  "Analyze the MAG7 fundamentally for their past earnings",
  "What profitable healthcare stocks have the lowest market cap?",
  "What was Microsoft's free cash flow in 2024?",
  "What was Apple's free cash flow in the past 4 quarters?",
  "What stock has the highest total assets?",
  "What financial services stock have the highest 1-year net income increase (in terms of dollars)?",
  "What automotice stock have the highest 1-year net income increase (in terms of percentage)?",
  "What are the most fundamentally strong space stocks?",
  "What is the average P/E ratio, P/S ratio, and FcF of Meta, Amazon, Google, Netflix, Nvidia, and Microsoft?",
  "What industries had the highest percent gain in 2024?",
  "What stocks had the highest drop (in terms of dollars) in the past 2 weeks?",
  "What stocks had the highest drop (in terms of percentage) in the past 2 weeks?",
  "What stocks with a market cap between $10 and $250 billion have a 5-year net income CAGR of at least 15%?",
  "What consumer goods stocks with a net income above $10 billion had the highest percent drop in the past 2 months?",
  "What airline stocks are up the most year-to-date?",
  "What semiconductor stocks have at least a 20% net income increase from 2022 to 2024? Sort by market cap descending",
];

const additionalQuestions = [
  "What AI stocks with a 4 year consistently increasing net income have the lowest 14 day RSI?",
  "What cloud computing stocks with a fundamental ranking between 3 and 4 have the most number of standard deviations from their 200 day average price?",
  "What banking stocks are the most below their 7 day exponential moving average?",
  "What semiconductor stocks have the highest 7 day increase in market cap in 2022?",
  "What AI stocks other than the MAG7 have the highest net income increase from 2022 to 2024?",
];
